[functions]
directory = "functions"

# [[redirects]]
# # Do not push this redirect to a versioned branch!
# from = "/1.0/*"
# to = "https://v1--cocky-brown-b1def5.netlify.app/:splat"
# status = 301
# force = true

# [[redirects]]
# # Do not push this redirect to a versioned branch!
# from = "/*"
# to = "https://v1--cocky-brown-b1def5.netlify.app/:splat"
# status = 301
# force = true
